const counterTypes = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  SET_COUNTER: 'SET_COUNTER',
  ASYNC_INCREASE_START: 'ASYNC_INCREASE_START',
  ASYNC_INCREASE_END: 'ASYNC_INCREASE_END',
  ASYNC_INCREASE_ERROR: 'ASYNC_INCREASE_ERROR',
}

export default counterTypes
